# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0006_auto_20170312_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('collection', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='particular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionsdeposits.Particular'),
        ),
        migrations.AddField(
            model_name='collection',
            name='payor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
