# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='residents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident', verbose_name='resident name'),
        ),
    ]
