# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_auto_20170311_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='residents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident', verbose_name='Name'),
        ),
    ]
