# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_auto_20170321_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='residents',
            new_name='resident',
        ),
    ]
