# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0004_auto_20170322_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='position',
            field=models.CharField(choices=[('chair', 'Chairman'), ('council', 'Councilor'), ('sec', 'Secretary'), ('tre', 'Treasurer')], default='', max_length=50),
        ),
    ]
