# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0006_auto_20170323_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='position',
            field=models.CharField(choices=[('chair', 'Chairman'), ('sec', 'Secretary'), ('treasure', 'Treasurer'), ('council', 'Councilor')], default='', max_length=50),
        ),
    ]
