# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0010_auto_20170408_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='question1',
            field=models.CharField(choices=[('question1_1', 'What is the first name of your best friend in high school?'), ('question1_2', 'What was the name of your first pet?'), ('question1_3', 'What was the first thing you learned to cook?'), ('question1_4', 'What was the first film you saw in the theater?'), ('question1_5', 'Where did you go the first time you flew on a plane?'), ('question1_6', 'What is the last name of your favorite elementary school teacher?')], max_length=50, verbose_name='Security Question 1'),
        ),
    ]
