# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='residents/')),
                ('fname', models.CharField(max_length=50, verbose_name='first name')),
                ('mname', models.CharField(max_length=50, verbose_name='middle name')),
                ('lname', models.CharField(max_length=50, verbose_name='last name')),
                ('bdate', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='0000-00-00', max_length=1)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('civil_status', models.CharField(choices=[('s', 'Single'), ('m', 'Married'), ('w', 'Widowed'), ('se', 'Separated'), ('d', 'Divorced')], max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('educational_attainment', models.CharField(choices=[('col', 'College'), ('hs', 'High school'), ('elem', 'Elementary')], default='', max_length=50, null=True)),
                ('spouse', models.CharField(blank=True, max_length=50)),
                ('children', models.IntegerField(blank=True, default=0)),
                ('date_of_delivery', models.DateField(blank=True)),
                ('lactating', models.BooleanField(default=False)),
                ('common_garbage_disposal', models.CharField(blank=True, max_length=50)),
                ('practice_family_planning', models.CharField(blank=True, max_length=50)),
                ('source_of_water_supply', models.CharField(blank=True, max_length=50)),
                ('toilet_type', models.CharField(blank=True, max_length=50)),
                ('common_agri_products', models.CharField(blank=True, max_length=50, verbose_name='common agri-products')),
                ('kinds_of_animals', models.CharField(blank=True, max_length=50)),
                ('other_agri_products', models.CharField(blank=True, max_length=50, verbose_name='other agri-products')),
                ('type_of_dwelling_unit', models.CharField(blank=True, max_length=50)),
                ('iodized_salt', models.BooleanField(default=False)),
                ('sangkap_pinoy_seal_product', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('act', 'Active'), ('dec', 'Decease'), ('tr', 'Transferred')], default='act', max_length=50)),
            ],
        ),
    ]
