# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_auto_20170311_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=1),
        ),
    ]
