# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_auto_20170311_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='date_of_delivery',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='iodized_salt',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='lactating',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='other_agri_products',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='practice_family_planning',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='sangkap_pinoy_seal_product',
        ),
    ]
