# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_auto_20170311_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(choices=[('s', 'Single'), ('m', 'Married'), ('w', 'Widowed'), ('se', 'Separated'), ('d', 'Divorced')], default='', max_length=50),
        ),
    ]
