# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_auto_20170312_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='spouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
