# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_auto_20170316_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.CharField(default='Dili, Bauang La Union', max_length=50),
        ),
    ]
