# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170322_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='official',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.Official', verbose_name='id no'),
        ),
    ]
