# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170228_1657'),
        ('officials', '0007_auto_20170324_1531'),
        ('attendance', '0005_auto_20170322_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceResident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attended', models.DateField(auto_now_add=True)),
                ('time_attended', models.TimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.Official', verbose_name='id no')),
            ],
        ),
    ]
