# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceofficial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='official',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
