# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20170405_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident', verbose_name='attendee'),
        ),
    ]
