# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20170307_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
